# Soluções relativas aos execícios da Aula 10

## Exercício 3

Implementar o algoritmo de encontrar auto valores usando a decomposição QR

In [1]:
import numpy as np

def eig_qr(matrix, iterations=100):
    temp = matrix.copy()
    for i in range(iterations):
        Q, R = np.linalg.qr(temp)
        temp = R.dot(Q)
    return np.diag(R)

np.random.seed(1234)
A = np.random.rand(3,3)
A = A + A.T
eig_vals = eig_qr(A)
print(A, end="\n\n")
print(eig_vals)

[[ 0.3830389   1.40746735  0.71419199]
 [ 1.40746735  1.55995162  1.07446478]
 [ 0.71419199  1.07446478  1.91627871]]

[-3.52909764 -0.88420795 -0.55403637]
